export const API = "https://testknock-questions.onrender.com/api";
export const API2 = "https://ourntamockpapers.onrender.com/api";

export const subjects = [
  { subjectName: "Accounting", image: '/syllabusImages/amico.png', link: "https://cdnasb.samarth.ac.in/site-admin23/syllabus/Final+Accountancy+12+March+2023.pdf" },
  { subjectName: "Agriculture", image: '/syllabusImages/rice-field/rafiki.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus%20of%20CUET%20%28UG%29%20-%202022/302_AGRICULTURE.pdf" },
  { subjectName: "Anthropology", image: '/syllabusImages/Sandy_Edu-04_Single-03 4.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus%20of%20CUET%20%28UG%29%20-%202022/303_Anthropology.pdf" },
  { subjectName: "Art Education Sculpture", image: '/syllabusImages/art/cuate.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus%20of%20CUET%20%28UG%29%20-%202022/312_ArtEducation_Painting&Sculpture.pdf" },
  { subjectName: "Biology", image: '/syllabusImages/biologist/rafiki.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus%20of%20CUET%20%28UG%29%20-%202022/304_BIOLOGY.pdf" },
  { subjectName: "Business Studies", image: '/syllabusImages/Business startup statistics and insights.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus%20of%20CUET%20%28UG%29%20-%202022/305_BusinessStudeis.pdf" },
  { subjectName: "Chemistry", image: '/syllabusImages/science/pana.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus%20of%20CUET%20%28UG%29%20-%202022/306_Chemistry.pdf" },
  { subjectName: "Computer Science", image: '/syllabusImages/researching/amico.png', link: "https://cdnasb.samarth.ac.in/site-admin23/syllabus/Final+Computer+Science+12+March+2023.pdf" },
  { subjectName: "Economics/Business Economics", image: '/syllabusImages/Financial growth.png', link: "https://cdnasb.samarth.ac.in/site-admin23/syllabus/Final+Economics+12+March+2023.pdf" },
  { subjectName: "Languages (IA & IB)", image: '/syllabusImages/learning-languages/pana.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus%20of%20CUET%20%28UG%29%20-%202022/LanguageSyllabus(IAandIB).pdf" },
  { subjectName: "Engineering Graphics", image: '/syllabusImages/Sandy_Edu-04_Single-03 4.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus%20of%20CUET%20%28UG%29%20-%202022/310_Eng.Graphics.pdf" },
  { subjectName: "Entrepreneurship", image: '/syllabusImages/Sandy_Edu-04_Single-03 4.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus%20of%20CUET%20%28UG%29%20-%202022/311_Entrepreneurship_.pdf" },
  { subjectName: "Environmental Studies", image: '/syllabusImages/nature/cuate.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus%20of%20CUET%20%28UG%29%20-%202022/307_EnvironmentalStudies.pdf" },
  { subjectName: "General Test", image: '/syllabusImages/online-test/rafiki.png', link: "https://cdnasb.samarth.ac.in/site-admin23/syllabus/501_General_Test.pdf" },
  { subjectName: "Legal Studies", image: '/syllabusImages/law-firm/amico.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus%20of%20CUET%20%28UG%29%20-%202022/317_LegalStudies.pdf" },
  { subjectName: "Geography", image: '/syllabusImages/Sandy_Edu-04_Single-03 4.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus%20of%20CUET%20%28UG%29%20-%202022/313_GEOGRAPHYGEOLOGY.pdf" },
  { subjectName: "History", image: '/syllabusImages/time-machine/rafiki.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus%20of%20CUET%20%28UG%29%20-%202022/314_History.pdf" },
  { subjectName: "Home Science", image: '/syllabusImages/Sandy_Edu-04_Single-03 4.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus%20of%20CUET%20%28UG%29%20-%202022/315_HOMESCIENCE.pdf" },
  { subjectName: "Knowledge Tradition -Practices India", image: '/syllabusImages/Sandy_Edu-04_Single-03 4.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus%20of%20CUET%20%28UG%29%20-%202022/316_KnowledgeTraditions.pdf" },
  { subjectName: "Mass Media/ Mass Communication", image: '/syllabusImages/marketing/rafiki.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus%20of%20CUET%20%28UG%29%20-%202022/318_MassMedia.pdf" },
  { subjectName: "Mathematics", image: '/syllabusImages/mathematics/amico.png', link: "https://cdnasb.samarth.ac.in/site-admin23/syllabus/Final_Mathematics+12+March+2023.pdf" },
  { subjectName: "Performing Arts", image: '/syllabusImages/acting/amico.png', link: "https://cdnasb.samarth.ac.in/site-admin23/syllabus/Final+Performing+Arts+12+March+2023.pdf" },
  { subjectName: "Physical Education", image: '/syllabusImages/physical-education/pana.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus%20of%20CUET%20%28UG%29%20-%202022/321_PhysicalEducation.pdf" },
  { subjectName: "Physics", image: '/syllabusImages/researching/amico.png', link: "https://cdnasb.samarth.ac.in/site-admin23/syllabus/Final+Physics+12+March+2023.pdf" },
  { subjectName: "Political Science", image: '/syllabusImages/Political debates.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus%20of%20CUET%20%28UG%29%20-%202022/323_politicalscience.pdf" },
  { subjectName: "Psychology", image: '/syllabusImages/group-therapy/rafiki.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus%20of%20CUET%20%28UG%29%20-%202022/324_Psychology.pdf" },
  { subjectName: "Sanskrit", image: '/syllabusImages/Sandy_Edu-04_Single-03 4.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus+of+CUET+(UG)+-+2022/325_Sanskrit_Domain.pdf" },
  { subjectName: "Sociology", image: '/syllabusImages/Business statistics.png', link: "https://cdnasb.samarth.ac.in/site/Syllabus%20of%20CUET%20%28UG%29%20-%202022/326_sociology.pdf" },
  { subjectName: "Teaching Aptitide", image: '/syllabusImages/online-test/rafiki.png', link: "https://cdnasb.samarth.ac.in/site-admin23/syllabus/327_TeachingAptitude.pdf" },
];
export const topics = {
  "General English": [
    "Spot the Error",
    "Sentence Correction",
    "Fill in the Blanks Single",
    "Fill in the Blanks Double",
    "Cloze Test",
    "Synonyms",
    "Antonyms",
    "One Word Substitution",
    "Idioms & Phrases",
    "Miscellaneous",
    "Jumbled Sentences & Parajumble",
    "Reading Comprehension"
  ],
  "General Test": [
    "Number System",
    "Algebra",
    "Simplification & Calculation",
    "Average",
    "Percentage",
    "Fraction & Decimals, Square root",
    "Ratio & Proportion",
    "Profit & Loss",
    "S.I & C.I , partnership",
    "Time, Speed & Distance",
    "Time & Work",
    "Mensuration",
    "Geometry",
    "Permutation & Combination",
    "Probability",
    "General Awareness"
  ],
  "Domain": {
    "Science": {
      "Maths": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Physics": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Chemistry": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Biology": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ]
    },
    "Commerce": {
      "Accountancy": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Economics": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Business Studies": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Mathematics": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ]
    },
    "Humanities & Social Sciences": {
      "History": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Political Science": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Geography": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Psychology": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Sociology": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Mathematics": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ]
    }
  }
};

export const topics2 = {
  Mathematics: [
    "Number System",
    "Algebra",
    "Simplification & Calculation",
    "Average",
    "Percentage",
    "Fraction and Decimals, Square root",
    "Ratio & Proportion",
    "Profit & Loss",
    "S.I & C.I, Partnership",
    "Time, Speed & Distance",
    "Time & Work",
    "Mensuration",
    "Geometry",
    "Permutation & Combination",
    "Probability"
  ],
  "Logical Reasoning": [
    "Alphabet series",
    "Blood Relation",
    "Classification",
    "Clock and Calendar",
    "Critical Reasoning",
    "Arrangement Circular and Linear",
    "Coding Decoding",
    "Decision Making and Order and Ranking",
    "Direction Problem",
    "Number Series",
    "Puzzle",
    "Venn Diagram",
    "Visual Reasoning"
  ],
  "General Awareness": [
    "Art Culture and Literature",
    "Award and Honor",
    "Indian Geography",
    "Indian Economics",
    "Indian History",
    "Indian Polity",
    "General Science",
    "International Cooperation Organization"
  ]
};
