export const API = "http://localhost:8800/api";
export const API2 = "https://ourntamockpapers.onrender.com/api";

export const topics = {
  "General English": [
    "Spot the Error",
    "Sentence Correction",
    "Fill in the Blanks - Single",
    "Fill in the Blanks - Double",
    "Cloze Test",
    "Synonyms",
    "Antonyms",
    "One Word Substitution",
    "Idioms & Phrases",
    "Miscellaneous",
    "Jumbled Sentences & Parajumble",
    "Reading Comprehension"
  ],
  "General Test": [
    "Number System",
    "Algebra",
    "Simplification & Calculation",
    "Average",
    "Percentage",
    "Fraction & Decimals, Square root",
    "Ratio & Proportion",
    "Profit & Loss",
    "S.I & C.I , partnership",
    "Time, Speed & Distance",
    "Time & Work",
    "Mensuration",
    "Geometry",
    "Permutation & Combination",
    "Probability",
    "General Awareness"
  ],
  "Domain": {
    "Science": {
      "Maths": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Physics": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Chemistry": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Biology": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ]
    },
    "Commerce": {
      "Accountancy": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Economics": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Business Studies": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Mathematics": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ]
    },
    "Humanities & Social Sciences": {
      "History": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Political Science": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Geography": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Psychology": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Sociology": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ],
      "Mathematics": [
        "Number System",
        "Algebra",
        "Simplification & Calculation",
        "Average",
        "Percentage",
        "Fraction & Decimals, Square root",
        "Ratio & Proportion",
        "Profit & Loss",
        "S.I & C.I , partnership",
        "Time, Speed & Distance",
        "Time & Work",
        "Mensuration",
        "Geometry",
        "Permutation & Combination",
        "Probability",
        "General Awareness"
      ]
    }
  }
};
